a=int(input("Enter value of a:"))
b=int(input("Enter value of b:"))
c=int(input("Enter value of c:"))
if(a>b):
  print("a is greater than b")
elif(b>c):
  print("b is greater than c")
elif(a>c):
  print("a is greater than c")
else:
  print("c is greater in all cases")
print("***ARITHMETIC OPERATIONS***")
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a//b)
print(b+c)
print(b-c)
print(b*c)
print(b/c)
print(b**c)
print(b//c)
print(a+c)
print(a-c)
print(a*c)
print(a/c)
print(a**c)
print(a//c)
